import Head from "next/head";
import Image from "next/image";
import { Button } from "components/Button";
import {
	Container,
	ContainerCenter,
	ContainerContent,
	ContainerFlex,
} from "components/Container";
import { Input } from "components/Input";
import { Text } from "components/Text";
import styles from "styles/Home.module.css";
import React from "react";
import { useAuth } from "auth/AuthContext";
import { useRouter } from "next/router";

export default function Home() {
	const [userCred, setUserCred] = React.useState({ email: "", password: "" });
	const { user, login } = useAuth();
	const { router } = useRouter();

	async function handleSubmit(e) {
		e.preventDefault();
		console.log(user);
		try {
			await login(userCred.email, userCred.password);
			router.push("/welcome");
			console.log(router);
		} catch (error) {
			console.log(error);
		}
	}
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ContainerFlex>
				<ContainerCenter>
					<ContainerContent>
						<Container align="center" width="100%">
							<Container margin="80px 0 50px 0">
								<Text weight="500" size="40px" align="center">
									Welcome Back
								</Text>
								<Text color="#636364" align="center">
									Welcome back! Please enter your details.
								</Text>
							</Container>
							<form onSubmit={handleSubmit}>
								<Container margin="0 0 20px 0">
									<Text weight="600" pad="3px 0 3px 0">
										Email
									</Text>
									<Input
										type="text"
										placeholder="Enter Email"
										name="email"
										onChange={(e) =>
											setUserCred({
												...userCred,
												[e.target.name]: e.target.value,
											})
										}
									/>
								</Container>

								<Container margin="0 0 20px 0">
									<Text weight="600" pad="3px 0 3px 0">
										Password
									</Text>
									<Input
										type="password"
										placeholder="Password"
										name="password"
										onChange={(e) =>
											setUserCred({
												...userCred,
												[e.target.name]: e.target.value,
											})
										}
									/>
								</Container>
								<Container
									direction="row"
									justify="space-between"
									margin="0 0 20px 0"
								>
									<Container direction="row" width="auto" align="center">
										<Input type="checkbox" width="auto" />
										<Text>Remember me</Text>
									</Container>
									<Text>Forgot password</Text>
								</Container>
								<Container margin="0 0 15px 0">
									<Button fill="#EA454C" shadow={true} type="submit">
										<Text color="#fff" pad="5px 0">
											Sign in
										</Text>
									</Button>
								</Container>
								<Container margin="0 0 20px 0">
									<Button border="1px solid rgba(0, 0, 0, 0.25)">
										<Container direction="row" justify="center" align="center">
											<Image
												src="/images/Google.svg"
												alt="google"
												width="25px"
												height="25px"
											/>
											<Text pad="0 0 0 5px">Sign in with Google</Text>
										</Container>
									</Button>
								</Container>
								<Container justify="center" direction="row">
									<Text>Don’t have an account? </Text>
									<Text disp="inline" color="#EA454C" pad="0 0 0 5px">
										Sign up fo free!
									</Text>
								</Container>
							</form>
						</Container>
					</ContainerContent>
					<ContainerContent bg="/images/bg.png"></ContainerContent>
				</ContainerCenter>
			</ContainerFlex>
		</div>
	);
}
